name: Deploy to EC2

on:
  push:
    branches:
      - main  # Se ejecutará cada vez que empujes cambios a 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Desplegar en EC2 vía SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            # 1. Navegar a la carpeta del proyecto en la EC2 (Ajusta la ruta según tu servidor)
            cd ~/hadercode.dev
            
            # 2. Descargar los últimos cambios desde tu repositorio
            git pull origin main
            
            # 3. Reconstruir los contenedores con las nuevas imágenes de Docker y borrar la caché vieja
            docker compose up -d --build
            
            # 4. (Opcional) Limpieza de imágenes huérfanas de Docker para no llenar el disco de la EC2
            docker image prune -f